BEGIN TRANSACTION;
CREATE TABLE "restaurant_food" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "name" varchar(50) NOT NULL, "descr" varchar(150) NOT NULL, "price" decimal NOT NULL);
INSERT INTO `restaurant_food` VALUES (8,'Sweet Roll','"Awh, did somebody steal your sweetroles?"',2.1);
INSERT INTO `restaurant_food` VALUES (9,'Apple Cabbage Stew','Restores 15 Health and 15 Stamina',8.5);
INSERT INTO `restaurant_food` VALUES (10,'Venison Stew','Restore Health 1 point for 720 seconds, Restore Stamina 1 point for 720 seconds',8.5);
INSERT INTO `restaurant_food` VALUES (11,'Apple Dumpling','Bows do 5% more damage for 60 seconds.',3.1);
INSERT INTO `restaurant_food` VALUES (12,'Venison Chop','Oh Deer!',7);
INSERT INTO `restaurant_food` VALUES (13,'Apple pie','Restores 10 health. Not much when fighting a giant.',5.5);
INSERT INTO `restaurant_food` VALUES (14,'Venison','Deer customer, try me!',6);
INSERT INTO `restaurant_food` VALUES (15,'Ash Hopper Leg','Well... Everyone it''s choice of food... right?',3);
INSERT INTO `restaurant_food` VALUES (16,'Vegetable Soup','Restore Health 1 point for 720 seconds <br />Restore Stamina 1 point for 720 seconds',5.5);
INSERT INTO `restaurant_food` VALUES (17,'Ash Hopper Meat','Someone sure got.... roasted',2.5);
INSERT INTO `restaurant_food` VALUES (18,'Tomato Soup','No, it''s to-MA-to',5.5);
INSERT INTO `restaurant_food` VALUES (19,'Tomato','It''s pronounced to-ma-TO',4.1);
INSERT INTO `restaurant_food` VALUES (20,'Ash Yam','Restores 1 health. So basically nothing.',1.1);
INSERT INTO `restaurant_food` VALUES (21,'Steamed Mudcrab Legs','It sounds just as disgusting as it is.',4.1);
INSERT INTO `restaurant_food` VALUES (22,'Baked potatoes.','Potato potato',2.1);
INSERT INTO `restaurant_food` VALUES (23,'Spiced Wine','Damage Stamina Regeneration 30 points for 50 seconds',7.5);
INSERT INTO `restaurant_food` VALUES (24,'Spiced Beef','Cow goes moooooo',4.5);
INSERT INTO `restaurant_food` VALUES (25,'Beef stew','Fortify Stamina 25 points for 720 seconds. Restore Stamina 2 points for 720 seconds.',8.5);
INSERT INTO `restaurant_food` VALUES (26,'Soul Husk','Interrupts the soul drain effect in the Soul Cairn <br />Resist 10% of magic for 10 seconds',1.1);
INSERT INTO `restaurant_food` VALUES (27,'Snowberry Crostata','Fire Resistance increases 4% for 60 seconds',5.2);
INSERT INTO `restaurant_food` VALUES (28,'Sliced Goat Cheese','Restores 15 points of Health',10);
INSERT INTO `restaurant_food` VALUES (29,'Sliced Eidar Cheese','Restores 15 points of Health',12);
INSERT INTO `restaurant_food` VALUES (30,'Boar meat','It''s meat from a boar. If you didn''t guess yet.',3);
INSERT INTO `restaurant_food` VALUES (31,'Seared Slaughterfish','You can''t cook this!',5.1);
INSERT INTO `restaurant_food` VALUES (32,'Salmon Steak','Many at the Blue Palace',4.1);
INSERT INTO `restaurant_food` VALUES (33,'Boiled Cream Treat','Give it to your adopted child as a gift!',4.5);
INSERT INTO `restaurant_food` VALUES (34,'Salmon Meat','Harvested from live Salmon!',3.1);
INSERT INTO `restaurant_food` VALUES (35,'Sack of Flour','Can be pickpocketed',1.5);
INSERT INTO `restaurant_food` VALUES (36,'Red Apple','Give it to adopted children as a gift!',3.1);
INSERT INTO `restaurant_food` VALUES (37,'Braided Bread','Carrying capacity increases by 5 for 30 seconds. Gianna can be pickpocketed for two. <br /> "Sneakthief!"',2.2);
INSERT INTO `restaurant_food` VALUES (38,'Raw Rabbit Leg','Superstition or actual luckbringers',2.1);
INSERT INTO `restaurant_food` VALUES (39,'Raw Beef','Raw beef has exactly the same model as Human Flesh',4.2);
INSERT INTO `restaurant_food` VALUES (40,'Bread','Well, it''s bread.',2.2);
INSERT INTO `restaurant_food` VALUES (41,'Rabbit Haunch','For other uses, see Rabbit',3.1);
INSERT INTO `restaurant_food` VALUES (42,'Butter','Well, it''s goes well with bread.',1.1);
INSERT INTO `restaurant_food` VALUES (43,'Potato Soup','Restore 10 points of Health<br /> Restore 10 points of Stamina.',5.5);
INSERT INTO `restaurant_food` VALUES (44,'Cabbage','"My cabbages!" ~ Another universe',2.25);
INSERT INTO `restaurant_food` VALUES (45,'Potato Bread','Baked by S''jirra in Faregyl Inn, south of the Imperial City in Cyrodiil',2.2);
INSERT INTO `restaurant_food` VALUES (46,'Cabbage Potato Soup','A soup made from salt piles, potatoes, cabbages and leeks.',5.5);
INSERT INTO `restaurant_food` VALUES (47,'Potato','Found in abandoned ruins in carts or chests',1.1);
INSERT INTO `restaurant_food` VALUES (48,'Cabbage Soup','The nightmare of the Cabbage guy.',5.5);
INSERT INTO `restaurant_food` VALUES (49,'Pheasant Roast','Shut up you filthy Pheasant!',4.2);
INSERT INTO `restaurant_food` VALUES (50,'Pheasant Breast','Pheasants are never seen alive, they are always dead',3.2);
INSERT INTO `restaurant_food` VALUES (51,'Carrot','For the rabbits beneath us.',1.1);
INSERT INTO `restaurant_food` VALUES (52,'Charred Skeever Meat','Why would one even eat this?',4.2);
INSERT INTO `restaurant_food` VALUES (53,'Mudcrab Legs','Obtained from dead mudcrabs!',3.1);
INSERT INTO `restaurant_food` VALUES (54,'Chicken Breast','"Attacked a chicken as soon as I got out of that intro cave. Biggest. Mistake. Ever."',3.2);
INSERT INTO `restaurant_food` VALUES (55,'Mead with Juniper Berry','Heals Stamina by 20 points, but lowers stamina regeneration by 30% for 40 seconds',5.5);
INSERT INTO `restaurant_food` VALUES (56,'Chicken Dumpling','Do not, under any circumstances, attack a chicken.',3.1);
INSERT INTO `restaurant_food` VALUES (57,'Mammoth Steak','Not commonly found in its prepared state',10);
INSERT INTO `restaurant_food` VALUES (58,'Mammoth Snout','The snout food item is much smaller than the snout on the mammoth itself',9);
INSERT INTO `restaurant_food` VALUES (59,'Clam Chowder','Made out of Clam meat, potatoes, milk and butter. Yum?',5.5);
INSERT INTO `restaurant_food` VALUES (60,'Clam meat','Ever heard of Clams? Me neither.',1);
INSERT INTO `restaurant_food` VALUES (61,'Mammoth Cheese Bowl','Restore Health (10 pts)<br />Restore Stamina (15 pts)',3.5);
INSERT INTO `restaurant_food` VALUES (62,'Cooked Beaf','Salted beef. Restores 10 health points.',5.5);
INSERT INTO `restaurant_food` VALUES (63,'Long Taffy Treat','has been spotted at or near Dragon locations',3.1);
INSERT INTO `restaurant_food` VALUES (64,'Leg of Goat Roast','Rather commonly dropped by bandits',5);
INSERT INTO `restaurant_food` VALUES (65,'Leg of Goat','Can be found on tables, in houses or in forts',4);
INSERT INTO `restaurant_food` VALUES (66,'Cooked Boar Meat','Made out of boar meat that has been cooked.',15.1);
INSERT INTO `restaurant_food` VALUES (67,'Leek','Loituma Girl approved!',1.1);
INSERT INTO `restaurant_food` VALUES (68,'Dog Meat','"Skyrim is now host to giant, flying lizards and two-legged cat-men, and you''re surprised by me? Yes. I just talked." - Barbas',3.2);
INSERT INTO `restaurant_food` VALUES (69,'Lavender Dumpling','Fortify Magicka 10 points for 60 seconds<br /> Magicka Resistance increases 10% for 60 seconds',3.1);
INSERT INTO `restaurant_food` VALUES (70,'Juniper Berry Crostata','Restore Health 2 points per second for 60 seconds',5.2);
INSERT INTO `restaurant_food` VALUES (71,'Eidar Cheese Wedge','It is a slice of an eidar cheese wheel.',5.25);
INSERT INTO `restaurant_food` VALUES (72,'Jazbay Crostata','Fortify Magicka 4 points for 60 seconds',5.2);
INSERT INTO `restaurant_food` VALUES (73,'Horse Meat','Commonly known as "Cow Meat"',5);
INSERT INTO `restaurant_food` VALUES (74,'Eidar Cheese Wheel','"and then the Dragonborn paused and ate 7 wheels of cheese, 13 breads, 3 portions of cooked boar meat and 32 leeches."',13.2);
INSERT INTO `restaurant_food` VALUES (75,'Elsweyr Fondue','If the Dragonborn is a Vampire and has the Necromage Restoration perk, the effects are increased to 31% for Magicka Regeneration and 125 for Fortify.',5.5);
INSERT INTO `restaurant_food` VALUES (76,'Horse Haunch','Sold in Oss',6);
INSERT INTO `restaurant_food` VALUES (77,'Horker Stew','Restore Health 1 point for 720 seconds',8.5);
INSERT INTO `restaurant_food` VALUES (78,'Fresh Meat','Thats right, TombRaiser. I always eat the meat just as i get it, because of its weight.',6.3);
INSERT INTO `restaurant_food` VALUES (79,'Horker Meat','Create a random unbound Dremora!',4);
INSERT INTO `restaurant_food` VALUES (80,'Horker Loaf','Horker Loaf is a food item',5);
INSERT INTO `restaurant_food` VALUES (81,'Garlic Bread','Cures all diseases. However, it is not particularly useful to a Dragonborn that is either a werewolf or a vampire.',2.1);
INSERT INTO `restaurant_food` VALUES (82,'Horker and Ash Yam Stew','Restore Health 16 pts <br />Restore Stamina 12 pts',9.5);
INSERT INTO `restaurant_food` VALUES (83,'Goat Cheese Wedge','It is a slice of a goat cheese wheel.',4.25);
INSERT INTO `restaurant_food` VALUES (84,'Honey Nut Treat','Honey, let''s go nuts!',2.1);
INSERT INTO `restaurant_food` VALUES (85,'Honey','Occasionally dropped by werebears',2.1);
INSERT INTO `restaurant_food` VALUES (86,'Goat Cheese Wheel','A pun here would be a little cheesy, right? Right?',10.2);
INSERT INTO `restaurant_food` VALUES (87,'Homecooked Meal','Increased Health, Magicka, & Stamina Regeneration',6);
INSERT INTO `restaurant_food` VALUES (88,'Gourd','The gourd appears to be based off of cushaw squash (Cucurbita argyrosperma).',1.2);
INSERT INTO `restaurant_food` VALUES (89,'Grilled Leeks','Loituma Girl approved even more!',2.1);
INSERT INTO `restaurant_food` VALUES (90,'Green Apple','You can either make dumplings out of them, or give them to your adopted children. Your choice.',3.1);
INSERT INTO `restaurant_food` VALUES (91,'Grilled Chicken Breast','Did you see the breasts on those chicks?',4.2);
INSERT INTO `restaurant_food` VALUES (92,'Lolly','"No lollygaggin''!"',0.5);
CREATE INDEX "restaurant_order_8a089c2a" ON "restaurant_order" ("account_id");
CREATE INDEX "restaurant_order_380b3cb5" ON "restaurant_order" ("food_id");
CREATE INDEX "restaurant_cardswipe_dcbdb4d6" ON "restaurant_cardswipe" ("card_id");
CREATE INDEX "restaurant_account_dcbdb4d6" ON "restaurant_account" ("card_id");
CREATE INDEX "django_session_de54fa62" ON "django_session" ("expire_date");
CREATE UNIQUE INDEX "django_content_type_app_label_76bd3d3b_uniq" ON "django_content_type" ("app_label", "model");
CREATE INDEX "django_admin_log_e8701ad4" ON "django_admin_log" ("user_id");
CREATE INDEX "django_admin_log_417f1b1c" ON "django_admin_log" ("content_type_id");
CREATE UNIQUE INDEX "auth_user_user_permissions_user_id_14a6b632_uniq" ON "auth_user_user_permissions" ("user_id", "permission_id");
CREATE INDEX "auth_user_user_permissions_e8701ad4" ON "auth_user_user_permissions" ("user_id");
CREATE INDEX "auth_user_user_permissions_8373b171" ON "auth_user_user_permissions" ("permission_id");
CREATE UNIQUE INDEX "auth_user_groups_user_id_94350c0c_uniq" ON "auth_user_groups" ("user_id", "group_id");
CREATE INDEX "auth_user_groups_e8701ad4" ON "auth_user_groups" ("user_id");
CREATE INDEX "auth_user_groups_0e939a4f" ON "auth_user_groups" ("group_id");
CREATE UNIQUE INDEX "auth_permission_content_type_id_01ab375a_uniq" ON "auth_permission" ("content_type_id", "codename");
CREATE INDEX "auth_permission_417f1b1c" ON "auth_permission" ("content_type_id");
CREATE UNIQUE INDEX "auth_group_permissions_group_id_0cd325b0_uniq" ON "auth_group_permissions" ("group_id", "permission_id");
CREATE INDEX "auth_group_permissions_8373b171" ON "auth_group_permissions" ("permission_id");
CREATE INDEX "auth_group_permissions_0e939a4f" ON "auth_group_permissions" ("group_id");
COMMIT;
