# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-02 00:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='payed',
            new_name='paid',
        ),
        migrations.AlterField(
            model_name='order',
            name='account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='restaurant.Account'),
        ),
    ]
