# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-02 10:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_auto_20161102_0024'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='chrono',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
