# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-02 15:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0005_auto_20161102_1518'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cardswipe',
            name='identifier',
        ),
        migrations.AddField(
            model_name='cardswipe',
            name='id',
            field=models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
