# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-02 15:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0006_auto_20161102_1521'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cardswipe',
            name='id',
        ),
        migrations.AddField(
            model_name='cardswipe',
            name='identifier',
            field=models.IntegerField(auto_created=True, default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
