# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-03 13:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0008_auto_20161102_1556'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': (('isCook', 'Can see available tasks'), ('isWaiter', 'Can change the status of tasks'), ('isCashier', 'Can remove a task by setting its status as closed')),
            },
        ),
    ]
