# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-03 14:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0010_auto_20161103_1400'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Permission',
        ),
    ]
